### ISSUE TITLE
Fuertecoin

### ISSUE THREAD

**Issue by le2Ks** [vaudois/stratum#1]

**Comment by vaudois** [comment]
this a private is no finished bug only and old version DELETE now!

**Comment by le2Ks** [comment]
> this a private is no finished bug only and old version DELETE now!

I can help on development side

**Comment by vaudois** [comment]
No help is needed, our latest version works fine and we are almost ready, we will soon publish it.

**Comment by le2Ks** [comment]
> No help is needed, our latest version works fine and we are almost ready, we will soon publish it.

Ok
